//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HUMAN_RESOURCES_v1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HUMAN_RESOURCES_Entities : DbContext
    {
        public HUMAN_RESOURCES_Entities()
            : base("name=HUMAN_RESOURCES_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CARGO> CARGOS { get; set; }
        public virtual DbSet<DEPARTAMENTO> DEPARTAMENTOS { get; set; }
        public virtual DbSet<EMPLEADO> EMPLEADOS { get; set; }
        public virtual DbSet<LICENCIA> LICENCIAS { get; set; }
        public virtual DbSet<NOMINA> NOMINAS { get; set; }
        public virtual DbSet<PERMISO> PERMISOS { get; set; }
        public virtual DbSet<SALIDA_EMPLEADOS> SALIDA_EMPLEADOS { get; set; }
        public virtual DbSet<VACACIONE> VACACIONES { get; set; }
    }
}
