//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HUMAN_RESOURCES_v1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SALIDA_EMPLEADOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SALIDA_EMPLEADOS()
        {
            this.EMPLEADOS = new HashSet<EMPLEADO>();
        }
         [Display(Name ="Salida Empleado")]
        public int id_salida_empleado { get; set; }
        [Display(Name = "Codigo Empleado")]
        public int id_emplado { get; set; }
        [Display(Name="Tipo de Salida")]
        public string tipo_salida { get; set; }
        [Display(Name="Fecha de Salida")]
        public System.DateTime feha_salida { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLEADO> EMPLEADOS { get; set; }
    }
}
