//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HUMAN_RESOURCES_v1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VACACIONE
    {
        public int id_vacaciones { get; set; }
        public int id_empleado { get; set; }
        public System.DateTime fecha_inicio_vacaciones { get; set; }
        public System.DateTime fecha_fin_vaciones { get; set; }
        public string comentario_vacaiones { get; set; }
    
        public virtual EMPLEADO EMPLEADO { get; set; }
    }
}
